<div style="page-break-after: always;">
<br><br>
Cyclos has login passwords and can also be configured for using special 
transaction passwords.

<i>Where to find it.</i><br>
You can change your login password via &quot;Menu: Personal > change password&quot;.<br>
For the transaction password refer to the related
<a href="#transaction_password"><u>help section</u></a>.
<br><br>
<span class="broker admin">
A member password can be changed via the profile of the member, section 
&quot;Access > manage passwords&quot;.
</span>
<hr>


<a NAME="change"></a>
<h3>Change login password</h3>
To change the password, fill out your current password and the new password
twice and click &quot;Submit&quot;. It is possible that password policies like
forbidding easy or obvious passwords have been activated. In such a case an
error message will appear when you chose a password that does not meet the
requirements defined in the policy. The message will inform you about the policy
and the allowed format of the password.
<br>
It is not allowed to chose a new password that you have used in the passed.
<span class="admin">If &quot;Force change on next login&quot; is checked the
member will be asked to change the password on the first login.<br>
If the group setting &quot;Send password by e-mail&quot; is enabled you will
have the extra option to automatically generate a new password and send it to
the member by clicking the submit button &quot;Reset password & send by
e-mail&quot;. In this case the password will be automatically generated, 
so you need not to fill in anything.</span>
<hr class="help">


<span class="admin">
According to the system (access) settings (&quot;Menu: Settings > access settings&quot;) 
the transaction password can be typed as number in a normal
form field or with a virtual keyboard. You can also choose the characters that will be
part of the transaction password.
The transaction password is managed at the user management page 
(&quot;profile > access > manage passwords&quot;). This option is only available if the
transaction password has been enabled for the group (in group permissions).
<hr class="help">
</span>


<a NAME="transaction_password_generation"></a>
<a name="transaction_password"></a>
<h3>Transaction password</h3>
A transaction password is a password that can be asked every time a user wants to make a payment. 
Here you can retrieve your personal. After clicking &quot;Get transaction password&quot; your 
password will be displayed. Make sure you remember your transaction password. You will only be 
able to retrieve the password once. 
<hr class="help">


<span class="admin">
<a NAME="manage_transaction_password"></a>
<h3>Manage transaction Password</h3>
<br>When the <a href="#transaction_password"><u>transaction password</u></a> is enabled
for the group it can have four different statuses.
<ul>
	<li><b>Inactive:</b> The transaction password has never been
	used/generated.
	<li><b>Pending:</b> The transaction password is pending to be generated by
	the member/admin.
	<li><b>Active:</b> The transaction password has been retrieved by the
	member.
	<li><b>Blocked:</b> The transaction password has been blocked by an
	administrator.
</ul>
This status is shown in this window. <br><br>
An administrator (with the appropriate permissions) can reset or block the transaction
password by clicking the button &quot;block transaction password&quot;. 
In this case the transaction password is
invalidated and the member will not receive a new one (until an admin resets it).<br><br>
You can also reset the transaction password via the button &quot;reset transaction
password&quot;. In this case the member will receive a new transaction password. 
<hr class="help">
</span>


<a name="pin"></a>
<h3>PIN</h3>
A PIN is a password which is used for some types of external payments, like POS (Point of Sale), 
paypal or payments via SMS. A PIN contains only numbers. <br><br>
<span class="admin">
To enable the PIN password, the following must be done:
<ul>
	<li><b>channel:</b> the PIN must be enabled in the <a href="${pagePrefix}settings#channels_detail"><u>
	channel</u></a> (&quot;Menu: settings > channels&quot;, and click on the edit icon to modify one).
	<li><b><a href="${pagePrefix}groups#edit_member_group"><u>
	group settings</u></a>:</b> Under &quot;access settings&quot; the PIN length must be set.
	<li><b> <a href="${pagePrefix}account_management#transaction_types"><u>
	transaction type</u></a>:</b> in the appropriate transaction type, the channel must be enabled.
</ul>
</span>
Pin and <a href="${pagePrefix}settings#channels"><u>channel</u></a> access can be reached via
<span class="admin">
the member <a href="${pagePrefix}profiles"><u>profile</u></a> > external access.
</span>
<span class="member">
&quot;Menu: Personal > external access&quot;.
</span>
<hr class="help">


<a NAME="change_pin"></a>
<h3>Change / Unblock PIN</h3>
A <a href="#pin"><u>PIN</u></a> is used for some types of external payments like POS (point of sale), paypal
or SMS payments.<br>
A PIN can only be numeric (no letters allowed). To change your PIN you have to
type your login password first. In case the
<a href="#transaction_password"><u>transaction password</u></a>
is used you have to enter that first (in stead of the login password). The PIN
must be entered twice and confirmed with the &quot;Submit&quot; button.<br><br>
When the PIN is entered wrongly it can be blocked after an amount of attempts (by default 3).
You can either wait until the blocking time has been expired or &quot;un-block&quot; the PIN
manually selecting the un-block button below the change PIN window.
<hr class="help">


<a NAME="select_channels"></a>
<h3>Channels</h3>
Here the possible
<span class="admin"> <a href="${pagePrefix}settings#channels"><u>channels</u></a>
are shown.</span>
<span class="member">channels are shown; a channels is a media via which
cyclos is accessed, for example the web via a browser, or a mobile phone. </span>
<br>
Not all may be available, depending on the configuration in your organization.
You can select the channels you want to use by checking the checkbox.
<ul>
	<li><b>POSWeb payments:</b> Point of sale payments (payments as consumer
	at shop).
	<li><b>WAP 1 access:</b> Mobile phone access for older models that support
	WAP 1 (Wireless Application Protocol 1). The mobile payment supports the saldo
	overview, browsing to payment history and payments.
	<li><b>WAP 2 access:</b> Mobile phone access for more modern mobile phones
	that support WAP 2 (Wireless Application Protocol 2). The mobile payment
	supports the saldo overview, browsing to payment history and payments.
	<li><b>Webshop payments:</b> Allow payments at external (e-commerce)
	sites. </u> Don't forget to click &quot;submit&quot; after having made your
	choices, otherwise the changes won't be saved.
</li></ul>
<b>Note: </b>The SMS channel can be activated in the notifications page. The link in 
the window (under the access channels) will lead you directly to that page. 
<hr class="help">

</div> <%--  page-break end --%>

<div class='help'>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
</div>